version: '3.9'
services:
  proxy:
    restart: on-failure
    build: ./proxy
    ports:
      - '6061:6061'
  frontend:
    restart: on-failure
    build: ./frontend
    ports:
      - '80:3000'
  nginx:
    build: ./nginx
    ports:
    - '80:80'
    depends_on:
    - proxy
    - frontend
